// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/d417f687ab0c81ed72bffbc5dace5f643369bb70/redux-immutable/redux-immutable.d.ts
declare module "redux-immutable" {
    export function combineReducers(reducers: Object): Redux.Reducer<any>;
}
